ARG BASE_IMAGE=pinot-base:latest
FROM ${BASE_IMAGE}

ENV PINOT_ROLE=broker \
    PINOT_HEAP_MIN=8g \
    PINOT_HEAP_MAX=8g \
    PINOT_GC_PROFILE=g1-low-pause \
    PINOT_CONFIG=/etc/pinot/broker.conf

EXPOSE 8099 8888

ENTRYPOINT ["/opt/pinot/bin/pinot-launcher.sh"]
CMD ["StartBroker"]
